name: Reusable workflow for linting R code in Jasp modules

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LINTR_COMMENT_BOT: true # ${{ github.event_name == 'pull_request' && 'true' || 'false' }}

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.1.3'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: lintr

      - name: Lint
        run: |
          library(lintr)

          undesirableFunctions <- with_defaults(
            default   = lintr::default_undesirable_functions,
            "sapply"  = "use vapply or purrr::map_<type>",
            ".v"      = "remove it",
            ".unv"    = "remove it",
            "options" = NULL
          )

          exclusions <- list(
            "R/RcppExports.R",
            "tests/testthat.R"
          )

          linters <- with_defaults(
            line_length_linter = line_length_linter(180),
            object_length_linter(50L),
            object_name_linter("camelCase"),
            undesirable_function_linter(undesirableFunctions),
            # these are too strict for now
            commented_code_linter = NULL,
            cyclocomp_linter = NULL
          )
          result <- lint_package(linters = linters, exclusions = exclusions)
          result
        shell: Rscript {0}
