name: Reusable workflow for linting R code in Jasp modules

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LINTR_COMMENT_BOT: true # ${{ github.event_name == 'pull_request' && 'true' || 'false' }}

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.1.3'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: lintr

      - name: Lint
        id: lint
        run: |         
          library(lintr)

          undesirableFunctions <- with_defaults(
            default   = lintr::default_undesirable_functions,
            "sapply"  = "use vapply or purrr::map_<type>",
            ".v"      = "remove it",
            ".unv"    = "remove it",
            "options" = NULL
          )

          exclusions <- list(
            "R/RcppExports.R",
            "tests/testthat.R"
          )

          linters <- with_defaults(
            line_length_linter = line_length_linter(180),
            object_length_linter(50L),
            object_name_linter("camelCase"),
            undesirable_function_linter(undesirableFunctions),
            # these are too strict for now
            commented_code_linter = NULL,
            cyclocomp_linter = NULL
          )
          result <- lint_package(linters = linters, exclusions = exclusions)
          
          formatLintResultByLinter <- function(lintResult, forGitHub = TRUE) {
            
            linterTypes <- vapply(lintResult, FUN.VALUE = character(1L), `[[`, "linter")
            splitX <- split(lintResult, linterTypes)
            
            if (forGitHub) {
                # TODO: check if github.actor is correct when someone retriggers a branch?
                base <- "${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}"
                print(paste("url base is", base))
            }
            bold <- if (forGitHub) paste else crayon::bold
            formattedString <- ""
            for (i in seq_along(splitX)) {
              if (forGitHub) {
                formattedString <- paste0(formattedString, "<details>\n<summary>", splitX[[i]][[1L]]$type, ": ", splitX[[i]][[1L]]$message, "</summary>\n")
              } else {
                color <- switch(splitX[[i]][[1L]]$type, warning = crayon::magenta, error = crayon::red, style = crayon::blue, crayon::bold)
                formattedString <- paste0(formattedString, color(splitX[[i]][[1L]]$type, ": ", sep = ""), crayon::bold(splitX[[i]][[1L]]$message))
              }
              for (x in splitX[[i]]) {
                # adapted from lintr:::print.lint
      
                lineInfo <- paste0(bold(x$filename, ":", as.character(x$line_number), ":", as.character(x$column_number), ": ", sep = ""))
                badCode  <- paste0(x$line, "\n", lintr:::highlight_string(x$message, x$column_number, x$ranges))
                
                if (forGitHub) {
                  lineInfo <- sprintf("[%s](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/%s#L%s)", lineInfo, x$filename, x$line_number)
                  formattedString <- paste0(formattedString, "\n", lineInfo, "\n```r\n", badCode, "\n```")
                } else {
                  formattedString <- paste0(formattedString, "\n", lineInfo, "\n", badCode)
                }
              }
              if (forGitHub) {
                formattedString <- paste0(formattedString, "\n</details>")
              } 
              formattedString <- paste0(formattedString, "\n\n")
            }
          
            if (formattedString != "") {
              formattedString <- paste0("The linter found the following issues:\n\n<details>\n<summary>List of issues</summary>\n", formattedString, "</details>")
            }
            formattedString
          }
          
          formattedString <- formatLintResultByLinter(result)
          #cat(formattedString)
          #envFile <- Sys.getenv("GITHUB_ENV")
          #cat(sprintf("\n\n\ntrying to write to %s", envFile))
          #con <- file(envFile, open = "a")
          #writeLines(sprintf("{lintrResults}={%s}", formattedString), con = con)
          #close(con)
          
          # based on https://trstringer.com/github-actions-multiline-strings/
          #cmd <- sprintf('
          #  echo "lintrResults2<<EOF" >> $GITHUB_ENV && 
          #  echo "%s" >> $GITHUB_ENV &&
          #  echo "EOF" >> $GITHUB_ENV
          #', formattedString)
          #cat(cmd)
          #cat("\n\n")
          #system(cmd)
          
          cat(formattedString, file = "formattedString.txt")
          
          splitInParts <- function(string, size = 1000) {
            pat <- paste0('(?<=.{', size, '})')
            strsplit(string, pat, perl = TRUE)[[1L]]
          }
          formattedStringSplit <- splitInParts(formattedString)
          print(length(formattedStringSplit))

          system(        'echo "lintrResults2<<EOF" >> $GITHUB_ENV')
          for (str in formattedStringSplit) {
            system(sprintf('echo "%s" >> $GITHUB_ENV', str))
          }
          system(        'echo "EOF" >> $GITHUB_ENV')
          
          # based on https://renehernandez.io/snippets/multiline-strings-as-a-job-output-in-github-actions/
          formattedString <- gsub("%",  "%25", formattedString)
          formattedString <- gsub("\n", "%0A", formattedString)
          formattedString <- gsub("\r", "%0D", formattedString)

          cmd <- sprintf('echo "{lintrResults}={%s}" >> $GITHUB_ENV', formattedString)
          cat(cmd)
          system(cmd)
          
          
          #cat(sprintf("{lintrResults}={%s}", formattedString), file = envFile, append = TRUE)
          #cmd <- sprintf('echo "{lintrResults}={%s}" >> $GITHUB_ENV', formattedString)
          #cmd <- sprintf('echo "::set-output name=lintrResults::%s"', formattedString)
          #cat(cmd)
          #system(cmd)
          
          result
        shell: Rscript {0}
      
      - name: put linter output into environment
        run: |
          cat "formattedString.txt"
          echo
          echo "lintrResults3<<EOF" >> $GITHUB_ENV
          cat "formattedString.txt" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash
      
      - name: display linter output
        run: |
          echo "The output is: ${{ env.lintrResults }}"
          echo "The output is: ${{ env.lintrResults2 }}"
          echo "The output is: ${{ env.lintrResults3 }}"
        shell: bash


      - name: Update initial comment
        uses: actions/github-script@v6
        with:
          script: |
            body = "${{ env.lintrResults }}";
            console.log(body);
            if (body != "") {
              github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body
              });
            }

      - name: fail if linter result is a non-empty string
        run: |
          if [ -z "${{ steps.lint.outputs.lintrResults }}" ]; then
            exit 1
          fi
        shell: bash
