name: Reusable workflow for linting R code in Jasp modules

on:
  workflow_call:

jobs:
  lint:
  
    # avoid duplicate runs on a pull request that is also a push, see https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/5
    # the check is inverted so that when a pr triggers both push and pr runs, the push run is skipped.
    if: github.event_name != 'push' || github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      #LINTR_COMMENT_BOT: true # ${{ github.event_name == 'pull_request' && 'true' || 'false' }}

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.1.3'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: lintr

      - name: Lint
        id: lint
        run: |         
          library(lintr)

          undesirableFunctions <- with_defaults(
            default   = lintr::default_undesirable_functions,
            "sapply"  = "use vapply or purrr::map_<type>",
            ".v"      = "remove it",
            ".unv"    = "remove it",
            "options" = NULL
          )

          exclusions <- list(
            "R/RcppExports.R",
            "tests/testthat.R"
          )

          linters <- with_defaults(
            line_length_linter = line_length_linter(180),
            object_length_linter(50L),
            object_name_linter("camelCase"),
            undesirable_function_linter(undesirableFunctions),
            # these are too strict for now
            commented_code_linter = NULL,
            cyclocomp_linter = NULL
          )
          result <- lint_package(linters = linters, exclusions = exclusions)
          
          formatLintResultByLinter <- function(lintResult, forGitHub = TRUE) {
            
            linterTypes <- vapply(lintResult, FUN.VALUE = character(1L), `[[`, "linter")
            splitX <- split(lintResult, linterTypes)
            
            if (forGitHub) {
                # TODO: check if github.actor is correct when someone retriggers a branch?
                base <- "${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}"
                print(paste("url base is", base))
            }
            bold <- if (forGitHub) paste else crayon::bold
            formattedString <- ""
            for (i in seq_along(splitX)) {
              if (forGitHub) {
                formattedString <- paste0(formattedString, "<details>\n<summary>", splitX[[i]][[1L]]$type, ": ", splitX[[i]][[1L]]$message, "</summary>\n")
              } else {
                color <- switch(splitX[[i]][[1L]]$type, warning = crayon::magenta, error = crayon::red, style = crayon::blue, crayon::bold)
                formattedString <- paste0(formattedString, color(splitX[[i]][[1L]]$type, ": ", sep = ""), crayon::bold(splitX[[i]][[1L]]$message))
              }
              for (x in splitX[[i]]) {
                # adapted from lintr:::print.lint
      
                lineInfo <- paste0(bold(x$filename, ":", as.character(x$line_number), ":", as.character(x$column_number), ": ", sep = ""))
                badCode  <- paste0(x$line, "\n", lintr:::highlight_string(x$message, x$column_number, x$ranges))
                
                if (forGitHub) {
                  lineInfo <- sprintf("[%s](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/%s#L%s)", lineInfo, x$filename, x$line_number)
                  formattedString <- paste0(formattedString, "\n", lineInfo, "\n```r\n", badCode, "\n```")
                } else {
                  formattedString <- paste0(formattedString, "\n", lineInfo, "\n", badCode)
                }
              }
              if (forGitHub) {
                formattedString <- paste0(formattedString, "\n</details>")
              } 
              formattedString <- paste0(formattedString, "\n\n")
            }
          
            if (formattedString != "") {
              formattedString <- paste0("The linter found the following issues:\n\n<details>\n<summary>List of issues</summary>\n", formattedString, "</details>")
            }
            formattedString
          }
          
          formattedString <- formatLintResultByLinter(result)
          # javascript has issues with '`'
          formattedString <- gsub("`", "\\`", formattedString, fixed = TRUE)
          
          con <- file(description = Sys.getenv("GITHUB_ENV"), open = "a")
          cat("LINTER_RESULTS<<LINTER_RESULTS_EOF\n", file = con, sep = "")
          cat(formattedString, "\n", file = con, sep = "")
          cat("LINTER_RESULTS_EOF", file = con)
          close(con)
          
          #Sys.setenv(LINTER_RESULTS=formattedString)
          #system('echo "LINTER_RESULTS<<EOF" >> $GITHUB_ENV')
          #system('echo "$LINTER_RESULTS" >> $GITHUB_ENV')
          #system('echo "EOF" >> $GITHUB_ENV')
          
          result
        shell: Rscript {0}
       
      - name: Update initial comment
        if: env.LINTER_RESULTS != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `${{ env.LINTER_RESULTS }}`
            });

      - name: fail if linter result is a non-empty string
        if: env.LINTER_RESULTS != ''
        run: |
          exit 1
        shell: bash
